using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace GoPlay.Generators.ProcessorRef
{
    /// <summary>
    /// 把 <see cref="MethodCandidate"/> 数组按 Processor 分组后，逐组产出一个扩展类源文件。
    /// 和 <see cref="ProcessorRefGenerator"/> 解耦，便于后续单测。
    /// </summary>
    internal static class Emitter
    {
        /// <param name="processorNamespace">目标 Processor 的命名空间；空字符串表示全局命名空间。</param>
        /// <param name="processorTypeName">目标 Processor 简名（用于生成扩展类名称）。</param>
        /// <param name="processorFullyQualifiedName">目标 Processor 的 <c>global::</c> 级完全限定名。</param>
        /// <param name="methods">同一 Processor 下所有通过筛选的 <see cref="MethodCandidate"/>。</param>
        public static string EmitExtensionClass(
            string processorNamespace,
            string processorTypeName,
            string processorFullyQualifiedName,
            IReadOnlyList<MethodCandidate> methods)
        {
            var sb = new StringBuilder(4096);
            sb.AppendLine("// <auto-generated/> — GoPlay.Generators.ProcessorRef");
            sb.AppendLine("// 禁止手工修改：由 [ProcessorApi] 驱动的增量生成器产物。");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using global::GoPlay.Core.Processors;");
            sb.AppendLine();

            sb.Append("namespace ").Append(ProcessorRefGenerator_GeneratedNamespace).AppendLine();
            sb.AppendLine("{");

            var className = processorTypeName + "RefExtensions";
            sb.Append("    /// <summary>Auto-generated extensions for <see cref=\"global::")
              .Append(processorFullyQualifiedName.StartsWith("global::") ? processorFullyQualifiedName.Substring("global::".Length) : processorFullyQualifiedName)
              .AppendLine("\"/>.</summary>");
            sb.Append("    public static class ").AppendLine(className);
            sb.AppendLine("    {");

            var isFirst = true;
            foreach (var m in methods)
            {
                if (!isFirst) sb.AppendLine();
                isFirst = false;
                EmitMethod(sb, processorFullyQualifiedName, m);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private const string ProcessorRefGenerator_GeneratedNamespace = "GoPlay.Generated.ProcessorRefs";

        private static void EmitMethod(StringBuilder sb, string processorFqn, MethodCandidate m)
        {
            // 决定该方法映射到哪个 ProcessorRef API
            //  - Fire=true + (void/Task/ValueTask) => Notify（fire-and-forget）
            //  - ReturnKind==Void => Notify
            //  - ReturnKind==Task / ValueTask => Request（无泛型版）
            //  - ReturnKind==TaskOfT / ValueTaskOfT => Request<T>
            //  - ReturnKind==Other（同步返回值）=> Request<T>，闭包里 Task.FromResult 包一层
            var dispatch = ResolveDispatch(m);
            if (dispatch == Dispatch.Skip) return;

            // 方法签名返回类型（对外暴露给调用方看到的类型）
            string returnType = dispatch switch
            {
                Dispatch.NotifyVoid => "void",
                Dispatch.NotifyFire => "void",
                Dispatch.RequestVoid => "global::System.Threading.Tasks.Task",
                Dispatch.RequestWithResult => $"global::System.Threading.Tasks.Task<{m.TaskResultDisplay}>",
                Dispatch.RequestSyncResult => $"global::System.Threading.Tasks.Task<{m.ReturnDisplay}>",
                _ => "void",
            };

            // 生成扩展方法
            sb.Append("        public static ").Append(returnType).Append(' ').Append(m.MethodName).Append('(');
            sb.Append("this global::GoPlay.Core.Processors.ProcessorRef<").Append(processorFqn).Append("> @ref");

            for (var i = 0; i < m.Parameters.Length; i++)
            {
                var p = m.Parameters[i];
                sb.Append(", ");
                if (p.IsParams) sb.Append("params ");
                sb.Append(p.TypeDisplay).Append(' ').Append(EscapeIdentifier(p.Name));
                if (p.HasExplicitDefault) sb.Append(" = ").Append(p.DefaultLiteral);
            }
            sb.AppendLine(")");

            // 方法体：所有 [ProcessorApi] 方法都带 routeKey 走 @ref.Request/Notify 的"带 routeKey"重载。
            // Runner 侧在邮箱分派时按 key 查方法级 sem：
            //   - 同时标 [Request]/[Notify]：命中 Route.MethodConcurrencySem，与客户端请求路径共享
            //   - 纯 [ProcessorApi]（无 Request/Notify）：命中 Runner 额外扫描建立的方法级 sem
            // ComputeRouteKey 对三种情况都返回非 null，所以理论上 routeKeyLit 恒非 null；
            // 保留 null 分支是为了兼容未来可能出现的"手写不想带 key"场景。
            var routeKeyLit = m.RouteKey is null ? null : SymbolDisplay.FormatLiteral(m.RouteKey, quote: true);

            sb.Append("            => ");
            switch (dispatch)
            {
                case Dispatch.NotifyVoid:
                    // 返回 void：包一层 async lambda 把同步调用包成 Task.CompletedTask
                    AppendInvocationHead(sb, "Notify", routeKeyLit);
                    sb.Append("__p => { __p.").Append(m.MethodName).Append('(');
                    AppendArgs(sb, m);
                    sb.AppendLine("); return global::System.Threading.Tasks.Task.CompletedTask; });");
                    break;
                case Dispatch.NotifyFire:
                    // 返回 Task 或 ValueTask：Fire=true 强制 Notify
                    if (m.ReturnKind == ReturnKind.ValueTask)
                    {
                        AppendInvocationHead(sb, "Notify", routeKeyLit);
                        sb.Append("__p => __p.").Append(m.MethodName).Append('(');
                        AppendArgs(sb, m);
                        sb.AppendLine(").AsTask());");
                    }
                    else
                    {
                        AppendInvocationHead(sb, "Notify", routeKeyLit);
                        sb.Append("__p => __p.").Append(m.MethodName).Append('(');
                        AppendArgs(sb, m);
                        sb.AppendLine("));");
                    }
                    break;
                case Dispatch.RequestVoid:
                    if (m.ReturnKind == ReturnKind.ValueTask)
                    {
                        AppendInvocationHead(sb, "Request", routeKeyLit);
                        sb.Append("__p => __p.").Append(m.MethodName).Append('(');
                        AppendArgs(sb, m);
                        sb.AppendLine(").AsTask());");
                    }
                    else
                    {
                        AppendInvocationHead(sb, "Request", routeKeyLit);
                        sb.Append("__p => __p.").Append(m.MethodName).Append('(');
                        AppendArgs(sb, m);
                        sb.AppendLine("));");
                    }
                    break;
                case Dispatch.RequestWithResult:
                    if (m.ReturnKind == ReturnKind.ValueTaskOfT)
                    {
                        AppendInvocationHead(sb, "Request", routeKeyLit);
                        sb.Append("__p => __p.").Append(m.MethodName).Append('(');
                        AppendArgs(sb, m);
                        sb.AppendLine(").AsTask());");
                    }
                    else
                    {
                        AppendInvocationHead(sb, "Request", routeKeyLit);
                        sb.Append("__p => __p.").Append(m.MethodName).Append('(');
                        AppendArgs(sb, m);
                        sb.AppendLine("));");
                    }
                    break;
                case Dispatch.RequestSyncResult:
                    // 同步返回值：用 Task.FromResult 包装，仍走 Request 走 mailbox
                    AppendInvocationHead(sb, "Request", routeKeyLit);
                    sb.Append("__p => global::System.Threading.Tasks.Task.FromResult(__p.")
                      .Append(m.MethodName).Append('(');
                    AppendArgs(sb, m);
                    sb.AppendLine(")));");
                    break;
            }
        }

        /// <summary>
        /// 生成 <c>@ref.Request(</c> 或 <c>@ref.Request("routekey", </c> 的开头片段。
        /// 有 routeKey 时走带 key 的重载，让 Runner 侧能匹配方法级 <c>[MaxConcurrency]</c>。
        /// </summary>
        private static void AppendInvocationHead(StringBuilder sb, string apiName, string? routeKeyLiteral)
        {
            sb.Append("@ref.").Append(apiName).Append('(');
            if (routeKeyLiteral != null)
            {
                sb.Append(routeKeyLiteral).Append(", ");
            }
        }

        private static void AppendArgs(StringBuilder sb, MethodCandidate m)
        {
            for (var i = 0; i < m.Parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(EscapeIdentifier(m.Parameters[i].Name));
            }
        }

        private static string EscapeIdentifier(string name)
        {
            return name switch
            {
                "ref" or "out" or "in" or "this" or "base" or "params"
                    or "class" or "struct" or "interface" or "namespace" or "new" or "var"
                    or "true" or "false" or "null" or "default" or "void" or "object"
                    or "string" or "int" or "long" or "short" or "byte" or "uint" or "ulong"
                    or "ushort" or "sbyte" or "float" or "double" or "decimal" or "bool"
                    or "char" or "static" or "public" or "private" or "internal" or "protected"
                    => "@" + name,
                _ => name,
            };
        }

        private enum Dispatch { Skip, NotifyVoid, NotifyFire, RequestVoid, RequestWithResult, RequestSyncResult }

        private static Dispatch ResolveDispatch(MethodCandidate m)
        {
            if (m.Fire)
            {
                // Fire=true 要求同步 void 或异步 Task/ValueTask；带返回值的方法已由 PROCREF003 拦截
                if (m.ReturnKind is ReturnKind.Void)
                    return Dispatch.NotifyVoid;
                if (m.ReturnKind is ReturnKind.Task or ReturnKind.ValueTask)
                    return Dispatch.NotifyFire;
                return Dispatch.Skip;
            }

            return m.ReturnKind switch
            {
                ReturnKind.Void => Dispatch.NotifyVoid,
                ReturnKind.Task or ReturnKind.ValueTask => Dispatch.RequestVoid,
                ReturnKind.TaskOfT or ReturnKind.ValueTaskOfT => Dispatch.RequestWithResult,
                // 同步返回非 Task 值：仍然走 mailbox，闭包里 Task.FromResult 包装
                ReturnKind.Other => Dispatch.RequestSyncResult,
                _ => Dispatch.Skip,
            };
        }
    }
}
