// Code generated by GoPlay Protocol Extension Generator. DO NOT EDIT.
using System;
using System.Threading.Tasks;
using GoPlay;
using GoPlay.Core.Protocols;

namespace GoPlayProj.Extension.Backend
{
    public static partial class ProtocolConsts
    {
        //Protocols
        
        //Pushes
    }

    public static partial class ClientExtensions
    {
        
    }
}